### ISSUE TITLE
getWorker improvment

### ISSUE THREAD

**Issue by killmenot** [robtweed/ewd-qoper8#10]
@robtweed 

Please take a look at https://github.com/robtweed/ewd-qoper8/blob/master/lib/master/proto/getWorker.js#L41-L42

What if no worker by pid here? Can we update
```js
worker = this.worker.process[pid];
if (worker.isAvailable) {
```
to
```js
worker = this.worker.process[pid];
if (worker && worker.isAvailable) {

```
?

**Comment by killmenot** [comment]
Same for `stopWorker` method here https://github.com/robtweed/ewd-qoper8/blob/master/lib/master/proto/stopWorker.js#L33

**Comment by robtweed** [comment]
Will be included in next build
