### ISSUE TITLE
build.js refactoring ideas

### ISSUE THREAD

**Issue by killmenot** [robtweed/ewd-qoper8#7]
Hi @robtweed 

What do you think if move [build](https://github.com/robtweed/ewd-qoper8/blob/master/lib/build.js) information to package.json? In this case we will have only one place with version in the module.

1. `no` -> package.json->version
2. `date` -> package.json->config->date (more about config [here](https://docs.npmjs.com/files/package.json#config))

In this case we can have the following

```js
var pkg = require('../package.json')

var build = {
  no: pkg.version,
  date: pkg.config.date,
};

module.exports = build;
```

**Comment by robtweed** [comment]
Yes I'd be happy with that - it would be good to remove the redundancy of a separate build.js file
