### ISSUE TITLE
getStats ideas

### ISSUE THREAD

**Issue by killmenot** [robtweed/ewd-qoper8#8]
@robtweed 

`getStats` method for [master](https://github.com/robtweed/ewd-qoper8/blob/master/lib/master/proto/getStats.js#L40) and [worker](https://github.com/robtweed/ewd-qoper8/blob/master/lib/worker/proto/getStats.js) returns very similar uptime props. I found that master returns `uptime` prop but worker returns `upTime`. It may lead to potential issues. Can we unify this prop to avoid any possible confusion?

**Comment by robtweed** [comment]
Will be included in next build - both will return uptime
