### ISSUE TITLE
sendRequestToWorker question

### ISSUE THREAD

**Issue by killmenot** [robtweed/ewd-qoper8#9]
@robtweed 

Please take a look at https://github.com/robtweed/ewd-qoper8/blob/master/lib/master/proto/sendRequestToWorker.js#L32

What if `queue` has no items? Do we need to check `requestObj` to be non empty here?

**Comment by robtweed** [comment]
If sendRequestToWorker was invoked out of context, then strictly-speaking, you're correct that the queue could be empty.  However, it's only invoked by processQueue which, in turn, is only invoked when an item is added to the queue.  To date it's never been a problem.  However, it may be worth adding a check to ensure the queue has something in it - it wouldn't do any harm

**Comment by robtweed** [comment]
I'll add this to the start of this module in the next build:

  if (this.queue.length === 0) return;
